-- Direct SQL script to insert missing users
-- Run this in phpMyAdmin or via mysql command line
-- IDs will be auto-generated (AUTO_INCREMENT)
-- ULIDs will be NULL initially - run backfill command after insertion

-- Note: INSERT IGNORE will skip users that already exist by email
-- This prevents duplicate entries

-- User 1: Qamber Ali
INSERT IGNORE INTO `users` (`ulid`, `name`, `avatar`, `status`, `receipt_screenshot`, `email`, `phone`, `email_verified_at`, `password`, `game_pin_hash`, `is_in_game`, `game_pin_locked_until`, `game_pin_failed_attempts`, `role`, `referral_code`, `reseller_id`, `kyc_status`, `kyc_id_type`, `kyc_id_number`, `kyc_full_name`, `kyc_id_front_path`, `kyc_id_back_path`, `kyc_selfie_path`, `kyc_submitted_at`, `kyc_approved_at`, `company_name`, `investment_capacity`, `experience`, `wallet_address`, `token_balance`, `coin_price`, `two_factor_secret`, `two_factor_recovery_codes`, `two_factor_confirmed_at`, `remember_token`, `created_at`, `updated_at`) 
VALUES (NULL, 'Qamber Ali', NULL, 'online', NULL, 'purchase.depac@gmail.com', '+923153246256', '2025-12-02 11:59:36', '$2y$12$amS69EsElQECwXY29YkQlu4Ln9DEykdM7nVhjKlPgWiwgxVXay67G', NULL, 0, NULL, 0, 'investor', NULL, NULL, 'not_started', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2313987169778670', 0.00, NULL, NULL, NULL, NULL, NULL, '2025-12-02 11:58:51', '2025-12-02 11:59:36');

-- User 2: Ashfaq Ahmad
INSERT IGNORE INTO `users` (`ulid`, `name`, `avatar`, `status`, `receipt_screenshot`, `email`, `phone`, `email_verified_at`, `password`, `game_pin_hash`, `is_in_game`, `game_pin_locked_until`, `game_pin_failed_attempts`, `role`, `referral_code`, `reseller_id`, `kyc_status`, `kyc_id_type`, `kyc_id_number`, `kyc_full_name`, `kyc_id_front_path`, `kyc_id_back_path`, `kyc_selfie_path`, `kyc_submitted_at`, `kyc_approved_at`, `company_name`, `investment_capacity`, `experience`, `wallet_address`, `token_balance`, `coin_price`, `two_factor_secret`, `two_factor_recovery_codes`, `two_factor_confirmed_at`, `remember_token`, `created_at`, `updated_at`) 
VALUES (NULL, 'Ashfaq Ahmad', NULL, 'online', NULL, 'ashfaqsial92@gmail.com', '03095511454', '2025-12-02 12:19:23', '$2y$12$bk34VilgzMUr67ctr63dy.bj/aimBwNqjRIEawwlgUu87RpPCCy5a', NULL, 0, NULL, 0, 'investor', NULL, 11, 'pending', 'cnic', '3550103988415', 'Ashfaq Ahmad', 'kyc/54/ta1zbDUkoMsDVBcdwScqJMrVQaUNA6kcIQiKlMrN.jpg', 'kyc/54/RIBr4o6TLL3FYkG9dYe6yIDGPD8tTYY7WuiWH7Vu.jpg', 'kyc/54/3v8KzExHZ4xF0qU3R937bEWuiDjC5uIBZJApRuBE.jpg', '2025-12-02 12:49:16', NULL, NULL, NULL, NULL, '3449849948475459', 1000.00, NULL, NULL, NULL, NULL, NULL, '2025-12-02 12:18:39', '2025-12-02 12:49:16');

-- User 3: Mubeenasif
INSERT IGNORE INTO `users` (`ulid`, `name`, `avatar`, `status`, `receipt_screenshot`, `email`, `phone`, `email_verified_at`, `password`, `game_pin_hash`, `is_in_game`, `game_pin_locked_until`, `game_pin_failed_attempts`, `role`, `referral_code`, `reseller_id`, `kyc_status`, `kyc_id_type`, `kyc_id_number`, `kyc_full_name`, `kyc_id_front_path`, `kyc_id_back_path`, `kyc_selfie_path`, `kyc_submitted_at`, `kyc_approved_at`, `company_name`, `investment_capacity`, `experience`, `wallet_address`, `token_balance`, `coin_price`, `two_factor_secret`, `two_factor_recovery_codes`, `two_factor_confirmed_at`, `remember_token`, `created_at`, `updated_at`) 
VALUES (NULL, 'Mubeenasif', NULL, 'online', NULL, 'maharbadshah78600001@gmail.com', '923164008986', '2025-12-02 12:20:50', '$2y$12$iI9/.60ErI.PkMtxdCv6BOYoWsD1dJqZCJo8bqDR0UyiWSacFhpma', NULL, 0, NULL, 0, 'investor', NULL, NULL, 'not_started', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1087817154572410', 0.00, NULL, NULL, NULL, NULL, NULL, '2025-12-02 12:20:16', '2025-12-02 12:20:50');

-- User 4: Manoj gir
INSERT IGNORE INTO `users` (`ulid`, `name`, `avatar`, `status`, `receipt_screenshot`, `email`, `phone`, `email_verified_at`, `password`, `game_pin_hash`, `is_in_game`, `game_pin_locked_until`, `game_pin_failed_attempts`, `role`, `referral_code`, `reseller_id`, `kyc_status`, `kyc_id_type`, `kyc_id_number`, `kyc_full_name`, `kyc_id_front_path`, `kyc_id_back_path`, `kyc_selfie_path`, `kyc_submitted_at`, `kyc_approved_at`, `company_name`, `investment_capacity`, `experience`, `wallet_address`, `token_balance`, `coin_price`, `two_factor_secret`, `two_factor_recovery_codes`, `two_factor_confirmed_at`, `remember_token`, `created_at`, `updated_at`) 
VALUES (NULL, 'Manoj gir', NULL, 'online', NULL, 'manojgri555@gmail.com', '0346211170', '2025-12-02 13:38:57', '$2y$12$lUj2GoBibguLEy3EcRyiJuIuP2Pc2sJaEy10XLMchQgYKGTHR4Tca', NULL, 0, NULL, 0, 'investor', NULL, 11, 'not_started', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '6930398590504526', 0.00, NULL, NULL, NULL, NULL, '6qP89tcjgA2DiJdQeuT9HypfvGMOZiwGRUltEaAC0R0OloW3YWyP8bBPEmwH', '2025-12-02 13:37:21', '2025-12-02 13:38:57');

-- User 5: Sabir
INSERT IGNORE INTO `users` (`ulid`, `name`, `avatar`, `status`, `receipt_screenshot`, `email`, `phone`, `email_verified_at`, `password`, `game_pin_hash`, `is_in_game`, `game_pin_locked_until`, `game_pin_failed_attempts`, `role`, `referral_code`, `reseller_id`, `kyc_status`, `kyc_id_type`, `kyc_id_number`, `kyc_full_name`, `kyc_id_front_path`, `kyc_id_back_path`, `kyc_selfie_path`, `kyc_submitted_at`, `kyc_approved_at`, `company_name`, `investment_capacity`, `experience`, `wallet_address`, `token_balance`, `coin_price`, `two_factor_secret`, `two_factor_recovery_codes`, `two_factor_confirmed_at`, `remember_token`, `created_at`, `updated_at`) 
VALUES (NULL, 'Sabir', NULL, 'online', NULL, 'sabirzhob@gmail.com', '+923412915335', '2025-12-02 13:59:02', '$2y$12$wkI3gu./0kcr0LzOXsjEo.BkZ16/KxL4aesTdbEPcngaaJJcvuN3m', NULL, 0, NULL, 0, 'investor', NULL, NULL, 'not_started', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '6533607359511853', 0.00, NULL, NULL, NULL, NULL, NULL, '2025-12-02 13:58:34', '2025-12-02 13:59:02');

-- User 6: Muhammad Ahsan Raza
INSERT IGNORE INTO `users` (`ulid`, `name`, `avatar`, `status`, `receipt_screenshot`, `email`, `phone`, `email_verified_at`, `password`, `game_pin_hash`, `is_in_game`, `game_pin_locked_until`, `game_pin_failed_attempts`, `role`, `referral_code`, `reseller_id`, `kyc_status`, `kyc_id_type`, `kyc_id_number`, `kyc_full_name`, `kyc_id_front_path`, `kyc_id_back_path`, `kyc_selfie_path`, `kyc_submitted_at`, `kyc_approved_at`, `company_name`, `investment_capacity`, `experience`, `wallet_address`, `token_balance`, `coin_price`, `two_factor_secret`, `two_factor_recovery_codes`, `two_factor_confirmed_at`, `remember_token`, `created_at`, `updated_at`) 
VALUES (NULL, 'Muhammad Ahsan Raza', NULL, 'online', NULL, 'goodmen1991000@gmail.com', '03040364322', '2025-12-02 14:14:12', '$2y$12$44iLh1fR7h8Btke4ZS//z.TS.aTAV2mQ9x3F26J3KpISOFeOAqQm6', NULL, 0, NULL, 0, 'investor', NULL, 11, 'not_started', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '3744185696762061', 0.00, NULL, NULL, NULL, NULL, NULL, '2025-12-02 14:13:35', '2025-12-02 14:14:12');

-- User 7: Abubaker jutt
INSERT IGNORE INTO `users` (`ulid`, `name`, `avatar`, `status`, `receipt_screenshot`, `email`, `phone`, `email_verified_at`, `password`, `game_pin_hash`, `is_in_game`, `game_pin_locked_until`, `game_pin_failed_attempts`, `role`, `referral_code`, `reseller_id`, `kyc_status`, `kyc_id_type`, `kyc_id_number`, `kyc_full_name`, `kyc_id_front_path`, `kyc_id_back_path`, `kyc_selfie_path`, `kyc_submitted_at`, `kyc_approved_at`, `company_name`, `investment_capacity`, `experience`, `wallet_address`, `token_balance`, `coin_price`, `two_factor_secret`, `two_factor_recovery_codes`, `two_factor_confirmed_at`, `remember_token`, `created_at`, `updated_at`) 
VALUES (NULL, 'Abubaker jutt', NULL, 'online', NULL, 'jutt302417@gmail.com', '03021616879', '2025-12-02 14:56:32', '$2y$12$j7YM0FbWM2JBjybnk6pvauNrckrio4dyJcHGU1vc1mGdBTZcJtwEa', NULL, 0, NULL, 0, 'investor', NULL, NULL, 'not_started', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '9963245652736565', 0.00, NULL, NULL, NULL, NULL, NULL, '2025-12-02 14:55:40', '2025-12-02 14:56:32');

-- User 8: SHAH RUKH
INSERT IGNORE INTO `users` (`ulid`, `name`, `avatar`, `status`, `receipt_screenshot`, `email`, `phone`, `email_verified_at`, `password`, `game_pin_hash`, `is_in_game`, `game_pin_locked_until`, `game_pin_failed_attempts`, `role`, `referral_code`, `reseller_id`, `kyc_status`, `kyc_id_type`, `kyc_id_number`, `kyc_full_name`, `kyc_id_front_path`, `kyc_id_back_path`, `kyc_selfie_path`, `kyc_submitted_at`, `kyc_approved_at`, `company_name`, `investment_capacity`, `experience`, `wallet_address`, `token_balance`, `coin_price`, `two_factor_secret`, `two_factor_recovery_codes`, `two_factor_confirmed_at`, `remember_token`, `created_at`, `updated_at`) 
VALUES (NULL, 'SHAH RUKH', NULL, 'online', NULL, 'shahrukh1122b@gmail.com', '03045180918', '2025-12-02 15:13:39', '$2y$12$GAxcNBQ.lrbggWJEk/YKf.4sCI/hE7sbkn5rvRT1JzYslNSVfHZIS', NULL, 0, NULL, 0, 'investor', NULL, NULL, 'not_started', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2423025116317782', 0.00, NULL, NULL, NULL, NULL, NULL, '2025-12-02 15:13:13', '2025-12-02 15:13:39');

-- User 9: Khalid Hussain
INSERT IGNORE INTO `users` (`ulid`, `name`, `avatar`, `status`, `receipt_screenshot`, `email`, `phone`, `email_verified_at`, `password`, `game_pin_hash`, `is_in_game`, `game_pin_locked_until`, `game_pin_failed_attempts`, `role`, `referral_code`, `reseller_id`, `kyc_status`, `kyc_id_type`, `kyc_id_number`, `kyc_full_name`, `kyc_id_front_path`, `kyc_id_back_path`, `kyc_selfie_path`, `kyc_submitted_at`, `kyc_approved_at`, `company_name`, `investment_capacity`, `experience`, `wallet_address`, `token_balance`, `coin_price`, `two_factor_secret`, `two_factor_recovery_codes`, `two_factor_confirmed_at`, `remember_token`, `created_at`, `updated_at`) 
VALUES (NULL, 'Khalid Hussain', NULL, 'online', NULL, 'khalid.hussain388@gmail.com', '+923453161684', '2025-12-02 15:37:39', '$2y$12$eYDEuoXjaL8EsEfzuNGesOXk69/u5cjk8geZTGwJP54UmBdtbkorG', NULL, 0, NULL, 0, 'investor', NULL, NULL, 'not_started', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '3707452255156200', 0.00, NULL, NULL, NULL, NULL, NULL, '2025-12-02 15:36:59', '2025-12-02 15:37:39');

-- User 10: Muhammad Imran shahbaz
INSERT IGNORE INTO `users` (`ulid`, `name`, `avatar`, `status`, `receipt_screenshot`, `email`, `phone`, `email_verified_at`, `password`, `game_pin_hash`, `is_in_game`, `game_pin_locked_until`, `game_pin_failed_attempts`, `role`, `referral_code`, `reseller_id`, `kyc_status`, `kyc_id_type`, `kyc_id_number`, `kyc_full_name`, `kyc_id_front_path`, `kyc_id_back_path`, `kyc_selfie_path`, `kyc_submitted_at`, `kyc_approved_at`, `company_name`, `investment_capacity`, `experience`, `wallet_address`, `token_balance`, `coin_price`, `two_factor_secret`, `two_factor_recovery_codes`, `two_factor_confirmed_at`, `remember_token`, `created_at`, `updated_at`) 
VALUES (NULL, 'Muhammad Imran shahbaz', NULL, 'online', NULL, 'imran03139234110@gmail.com', '+923139234110', '2025-12-02 15:40:21', '$2y$12$AnsHOAQuCOyEPn18V.BMGuEynqJ5i4phNa7.P3MKq8gn3ordyc6Qe', NULL, 0, NULL, 0, 'investor', NULL, NULL, 'not_started', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '6420492589688106', 0.00, NULL, NULL, NULL, NULL, NULL, '2025-12-02 15:39:41', '2025-12-02 15:40:21');

-- User 11: Muhmmad Mudassar
INSERT IGNORE INTO `users` (`ulid`, `name`, `avatar`, `status`, `receipt_screenshot`, `email`, `phone`, `email_verified_at`, `password`, `game_pin_hash`, `is_in_game`, `game_pin_locked_until`, `game_pin_failed_attempts`, `role`, `referral_code`, `reseller_id`, `kyc_status`, `kyc_id_type`, `kyc_id_number`, `kyc_full_name`, `kyc_id_front_path`, `kyc_id_back_path`, `kyc_selfie_path`, `kyc_submitted_at`, `kyc_approved_at`, `company_name`, `investment_capacity`, `experience`, `wallet_address`, `token_balance`, `coin_price`, `two_factor_secret`, `two_factor_recovery_codes`, `two_factor_confirmed_at`, `remember_token`, `created_at`, `updated_at`) 
VALUES (NULL, 'Muhmmad Mudassar', NULL, 'online', NULL, 'mmudassar2008@gmail.com', '+923413606855', '2025-12-02 16:38:17', '$2y$12$SZIG74hTHCUAqMJG/snWj.QtKLEk7wdund1CkR5dr.YtF8DM9wNWO', NULL, 0, NULL, 0, 'investor', NULL, NULL, 'not_started', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1597804430177384', 0.00, NULL, NULL, NULL, NULL, NULL, '2025-12-02 16:37:39', '2025-12-02 16:38:17');

-- User 12: Rana Muhammad Faraz Hussain
INSERT IGNORE INTO `users` (`ulid`, `name`, `avatar`, `status`, `receipt_screenshot`, `email`, `phone`, `email_verified_at`, `password`, `game_pin_hash`, `is_in_game`, `game_pin_locked_until`, `game_pin_failed_attempts`, `role`, `referral_code`, `reseller_id`, `kyc_status`, `kyc_id_type`, `kyc_id_number`, `kyc_full_name`, `kyc_id_front_path`, `kyc_id_back_path`, `kyc_selfie_path`, `kyc_submitted_at`, `kyc_approved_at`, `company_name`, `investment_capacity`, `experience`, `wallet_address`, `token_balance`, `coin_price`, `two_factor_secret`, `two_factor_recovery_codes`, `two_factor_confirmed_at`, `remember_token`, `created_at`, `updated_at`) 
VALUES (NULL, 'Rana Muhammad Faraz Hussain', NULL, 'online', NULL, 'faraz5660@gmail.com', '+923120771725', '2025-12-02 17:43:25', '$2y$12$NKka2BPtaAhxGiGaDbZUx.rvzp79TqYxvX.vc8.CP03lTPeeTK.KS', NULL, 0, NULL, 0, 'investor', NULL, NULL, 'not_started', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '9551383553436292', 0.00, NULL, NULL, NULL, NULL, NULL, '2025-12-02 17:43:00', '2025-12-02 17:43:25');

-- User 13: Hafiz Muhammad Huzaifa
INSERT IGNORE INTO `users` (`ulid`, `name`, `avatar`, `status`, `receipt_screenshot`, `email`, `phone`, `email_verified_at`, `password`, `game_pin_hash`, `is_in_game`, `game_pin_locked_until`, `game_pin_failed_attempts`, `role`, `referral_code`, `reseller_id`, `kyc_status`, `kyc_id_type`, `kyc_id_number`, `kyc_full_name`, `kyc_id_front_path`, `kyc_id_back_path`, `kyc_selfie_path`, `kyc_submitted_at`, `kyc_approved_at`, `company_name`, `investment_capacity`, `experience`, `wallet_address`, `token_balance`, `coin_price`, `two_factor_secret`, `two_factor_recovery_codes`, `two_factor_confirmed_at`, `remember_token`, `created_at`, `updated_at`) 
VALUES (NULL, 'Hafiz Muhammad Huzaifa', NULL, 'online', NULL, 'huzaifamarketers@gmail.com', '+923126424127', '2025-12-03 05:08:06', '$2y$12$7vkX9utpkS121wyQtK/BVukMZUoHf4e.A8T4E7uvXgtoy8nj/21oG', NULL, 0, NULL, 0, 'investor', NULL, NULL, 'not_started', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2703755804502075', 0.00, NULL, NULL, NULL, NULL, NULL, '2025-12-03 05:07:27', '2025-12-03 05:08:06');

-- User 14: Kashif Nawaz
INSERT IGNORE INTO `users` (`ulid`, `name`, `avatar`, `status`, `receipt_screenshot`, `email`, `phone`, `email_verified_at`, `password`, `game_pin_hash`, `is_in_game`, `game_pin_locked_until`, `game_pin_failed_attempts`, `role`, `referral_code`, `reseller_id`, `kyc_status`, `kyc_id_type`, `kyc_id_number`, `kyc_full_name`, `kyc_id_front_path`, `kyc_id_back_path`, `kyc_selfie_path`, `kyc_submitted_at`, `kyc_approved_at`, `company_name`, `investment_capacity`, `experience`, `wallet_address`, `token_balance`, `coin_price`, `two_factor_secret`, `two_factor_recovery_codes`, `two_factor_confirmed_at`, `remember_token`, `created_at`, `updated_at`) 
VALUES (NULL, 'Kashif Nawaz', NULL, 'online', NULL, 'kn235500@gmail.com', '+923472563950', '2025-12-03 06:38:58', '$2y$12$UyeDQDqjKypDMH27mU1Yr.2QR/9mcl4YtuIyvfqjs4aNkvhrvcSk6', NULL, 0, NULL, 0, 'investor', NULL, 11, 'not_started', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '3389391768734997', 0.00, NULL, NULL, NULL, NULL, 'X0Ug97BPenKJtGlG5EYMNo7RCcZA202v3MpTIr0MMRPVEY6QNSkTDsb9p64E', '2025-12-03 06:37:23', '2025-12-03 06:38:58');

-- User 15: Muhammad Sayyam
INSERT IGNORE INTO `users` (`ulid`, `name`, `avatar`, `status`, `receipt_screenshot`, `email`, `phone`, `email_verified_at`, `password`, `game_pin_hash`, `is_in_game`, `game_pin_locked_until`, `game_pin_failed_attempts`, `role`, `referral_code`, `reseller_id`, `kyc_status`, `kyc_id_type`, `kyc_id_number`, `kyc_full_name`, `kyc_id_front_path`, `kyc_id_back_path`, `kyc_selfie_path`, `kyc_submitted_at`, `kyc_approved_at`, `company_name`, `investment_capacity`, `experience`, `wallet_address`, `token_balance`, `coin_price`, `two_factor_secret`, `two_factor_recovery_codes`, `two_factor_confirmed_at`, `remember_token`, `created_at`, `updated_at`) 
VALUES (NULL, 'Muhammad Sayyam', NULL, 'online', NULL, 'sayyamsaeed88@gmail.com', '+923238955927', '2025-12-03 07:44:41', '$2y$12$DZPeY3E7/YpkBEy9BJCZPu.AUIJeB./Kaj8JbocdX/CwXE4qkFI6W', NULL, 0, NULL, 0, 'investor', NULL, NULL, 'not_started', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '6861913826685108', 0.00, NULL, NULL, NULL, NULL, NULL, '2025-12-03 07:44:08', '2025-12-03 07:44:41');

-- User 16: Areeb ahmed
INSERT IGNORE INTO `users` (`ulid`, `name`, `avatar`, `status`, `receipt_screenshot`, `email`, `phone`, `email_verified_at`, `password`, `game_pin_hash`, `is_in_game`, `game_pin_locked_until`, `game_pin_failed_attempts`, `role`, `referral_code`, `reseller_id`, `kyc_status`, `kyc_id_type`, `kyc_id_number`, `kyc_full_name`, `kyc_id_front_path`, `kyc_id_back_path`, `kyc_selfie_path`, `kyc_submitted_at`, `kyc_approved_at`, `company_name`, `investment_capacity`, `experience`, `wallet_address`, `token_balance`, `coin_price`, `two_factor_secret`, `two_factor_recovery_codes`, `two_factor_confirmed_at`, `remember_token`, `created_at`, `updated_at`) 
VALUES (NULL, 'Areeb ahmed', NULL, 'online', NULL, 'aareeb850@gmail.com', '03402778511', '2025-12-03 08:16:05', '$2y$12$AcJiBUeCCEo1VeFLI3PoF.Yg9sUFwrlFRRWHi5btmCWMwFPxlOqaa', NULL, 0, NULL, 0, 'investor', NULL, NULL, 'not_started', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '8043044149456938', 0.00, NULL, NULL, NULL, NULL, NULL, '2025-12-03 08:15:38', '2025-12-03 08:16:05');

-- User 17: ahmedmawaz
INSERT IGNORE INTO `users` (`ulid`, `name`, `avatar`, `status`, `receipt_screenshot`, `email`, `phone`, `email_verified_at`, `password`, `game_pin_hash`, `is_in_game`, `game_pin_locked_until`, `game_pin_failed_attempts`, `role`, `referral_code`, `reseller_id`, `kyc_status`, `kyc_id_type`, `kyc_id_number`, `kyc_full_name`, `kyc_id_front_path`, `kyc_id_back_path`, `kyc_selfie_path`, `kyc_submitted_at`, `kyc_approved_at`, `company_name`, `investment_capacity`, `experience`, `wallet_address`, `token_balance`, `coin_price`, `two_factor_secret`, `two_factor_recovery_codes`, `two_factor_confirmed_at`, `remember_token`, `created_at`, `updated_at`) 
VALUES (NULL, 'ahmedmawaz', NULL, 'online', NULL, 'ahmedmawazsial@gmail.com', '03340569932', NULL, '$2y$12$/Oai5v5Ht1FdU80FL.CbAOVUT/TFfl1sie1Z9DBitY/SKo3qmrQaW', NULL, 0, NULL, 0, 'investor', NULL, NULL, 'not_started', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '4998978179549717', 0.00, NULL, NULL, NULL, NULL, NULL, '2025-12-03 09:01:06', '2025-12-03 09:01:06');

-- User 18: Muhammad Bilal
INSERT IGNORE INTO `users` (`ulid`, `name`, `avatar`, `status`, `receipt_screenshot`, `email`, `phone`, `email_verified_at`, `password`, `game_pin_hash`, `is_in_game`, `game_pin_locked_until`, `game_pin_failed_attempts`, `role`, `referral_code`, `reseller_id`, `kyc_status`, `kyc_id_type`, `kyc_id_number`, `kyc_full_name`, `kyc_id_front_path`, `kyc_id_back_path`, `kyc_selfie_path`, `kyc_submitted_at`, `kyc_approved_at`, `company_name`, `investment_capacity`, `experience`, `wallet_address`, `token_balance`, `coin_price`, `two_factor_secret`, `two_factor_recovery_codes`, `two_factor_confirmed_at`, `remember_token`, `created_at`, `updated_at`) 
VALUES (NULL, 'Muhammad Bilal', NULL, 'online', NULL, 'hadiqam2@gmail.com', '923442875475', '2025-12-03 09:28:42', '$2y$12$IBr5ieLdTUzX5sK1VZHKl./Sa7PJYOzZZZ.sEl8LGH.C8awBWUtUK', NULL, 0, NULL, 0, 'investor', NULL, NULL, 'not_started', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '7254531675549881', 0.00, NULL, NULL, NULL, NULL, NULL, '2025-12-03 09:28:16', '2025-12-03 09:28:42');

-- User 19: Muhammad Waseem
INSERT IGNORE INTO `users` (`ulid`, `name`, `avatar`, `status`, `receipt_screenshot`, `email`, `phone`, `email_verified_at`, `password`, `game_pin_hash`, `is_in_game`, `game_pin_locked_until`, `game_pin_failed_attempts`, `role`, `referral_code`, `reseller_id`, `kyc_status`, `kyc_id_type`, `kyc_id_number`, `kyc_full_name`, `kyc_id_front_path`, `kyc_id_back_path`, `kyc_selfie_path`, `kyc_submitted_at`, `kyc_approved_at`, `company_name`, `investment_capacity`, `experience`, `wallet_address`, `token_balance`, `coin_price`, `two_factor_secret`, `two_factor_recovery_codes`, `two_factor_confirmed_at`, `remember_token`, `created_at`, `updated_at`) 
VALUES (NULL, 'Muhammad Waseem', NULL, 'online', NULL, 'makki12374@yahoo.com', '+923226861086', NULL, '$2y$12$91T38BV/mJLXsHCehWfcBuchsy6invzzRpFh88Nf0WxBEh.DUF4S6', NULL, 0, NULL, 0, 'reseller', 'RSL74', NULL, 'not_started', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Muhammad Waseem', '50000', NULL, '7724973944205629', 0.00, NULL, NULL, NULL, NULL, NULL, '2025-12-03 10:17:52', '2025-12-03 10:17:52');

-- User 20: Hafiz Muhammad Muneer Ahmed Yousafi
INSERT IGNORE INTO `users` (`ulid`, `name`, `avatar`, `status`, `receipt_screenshot`, `email`, `phone`, `email_verified_at`, `password`, `game_pin_hash`, `is_in_game`, `game_pin_locked_until`, `game_pin_failed_attempts`, `role`, `referral_code`, `reseller_id`, `kyc_status`, `kyc_id_type`, `kyc_id_number`, `kyc_full_name`, `kyc_id_front_path`, `kyc_id_back_path`, `kyc_selfie_path`, `kyc_submitted_at`, `kyc_approved_at`, `company_name`, `investment_capacity`, `experience`, `wallet_address`, `token_balance`, `coin_price`, `two_factor_secret`, `two_factor_recovery_codes`, `two_factor_confirmed_at`, `remember_token`, `created_at`, `updated_at`) 
VALUES (NULL, 'Hafiz Muhammad Muneer Ahmed Yousafi', NULL, 'online', NULL, 'fazimuneer99@gmail.com', '+923064507007', '2025-12-03 11:10:58', '$2y$12$Y93Qf4SfWXUmMOdBkRd81.3kbqQTZXqNjpqiD6rUXOmyxmvY5shxO', NULL, 0, NULL, 0, 'investor', NULL, NULL, 'not_started', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '9325653189736225', 0.00, NULL, NULL, NULL, NULL, NULL, '2025-12-03 11:10:33', '2025-12-03 11:10:58');

-- User 21: Palak Naz
INSERT IGNORE INTO `users` (`ulid`, `name`, `avatar`, `status`, `receipt_screenshot`, `email`, `phone`, `email_verified_at`, `password`, `game_pin_hash`, `is_in_game`, `game_pin_locked_until`, `game_pin_failed_attempts`, `role`, `referral_code`, `reseller_id`, `kyc_status`, `kyc_id_type`, `kyc_id_number`, `kyc_full_name`, `kyc_id_front_path`, `kyc_id_back_path`, `kyc_selfie_path`, `kyc_submitted_at`, `kyc_approved_at`, `company_name`, `investment_capacity`, `experience`, `wallet_address`, `token_balance`, `coin_price`, `two_factor_secret`, `two_factor_recovery_codes`, `two_factor_confirmed_at`, `remember_token`, `created_at`, `updated_at`) 
VALUES (NULL, 'Palak Naz', NULL, 'online', NULL, 'advocatepalaknazmemon@gmail.com', '=923108802013', '2025-12-03 11:11:15', '$2y$12$RskkEGZoFGR8l8gF8b1k6.n93Cjqe8OBvkMuu/iZptCWifhFa7dye', NULL, 0, NULL, 0, 'investor', NULL, 11, 'not_started', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '5204762646732544', 3350.00, NULL, NULL, NULL, NULL, NULL, '2025-12-03 11:10:36', '2025-12-03 11:39:25');

-- User 22: Mirhazar
INSERT IGNORE INTO `users` (`ulid`, `name`, `avatar`, `status`, `receipt_screenshot`, `email`, `phone`, `email_verified_at`, `password`, `game_pin_hash`, `is_in_game`, `game_pin_locked_until`, `game_pin_failed_attempts`, `role`, `referral_code`, `reseller_id`, `kyc_status`, `kyc_id_type`, `kyc_id_number`, `kyc_full_name`, `kyc_id_front_path`, `kyc_id_back_path`, `kyc_selfie_path`, `kyc_submitted_at`, `kyc_approved_at`, `company_name`, `investment_capacity`, `experience`, `wallet_address`, `token_balance`, `coin_price`, `two_factor_secret`, `two_factor_recovery_codes`, `two_factor_confirmed_at`, `remember_token`, `created_at`, `updated_at`) 
VALUES (NULL, 'Mirhazar', NULL, 'online', NULL, 'mirhazarbugti57@gmail.com', '+92 3113564630', '2025-12-03 13:05:13', '$2y$12$.8BczRhE95Xxs4Ttzlk/P.9X57pRkpk9kUO/Uvv0zBi0mHrd7Vh4S', NULL, 0, NULL, 0, 'investor', NULL, NULL, 'not_started', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2359124475103485', 0.00, NULL, NULL, NULL, NULL, NULL, '2025-12-03 13:04:18', '2025-12-03 13:05:13');

-- User 23: M Shahbaz
INSERT IGNORE INTO `users` (`ulid`, `name`, `avatar`, `status`, `receipt_screenshot`, `email`, `phone`, `email_verified_at`, `password`, `game_pin_hash`, `is_in_game`, `game_pin_locked_until`, `game_pin_failed_attempts`, `role`, `referral_code`, `reseller_id`, `kyc_status`, `kyc_id_type`, `kyc_id_number`, `kyc_full_name`, `kyc_id_front_path`, `kyc_id_back_path`, `kyc_selfie_path`, `kyc_submitted_at`, `kyc_approved_at`, `company_name`, `investment_capacity`, `experience`, `wallet_address`, `token_balance`, `coin_price`, `two_factor_secret`, `two_factor_recovery_codes`, `two_factor_confirmed_at`, `remember_token`, `created_at`, `updated_at`) 
VALUES (NULL, 'M Shahbaz', NULL, 'online', NULL, 'hafizshahbazlqp@gmail.com', '03130067078', '2025-12-03 14:09:17', '$2y$12$ieqb6b9JcgC.NiNHrQ3i3eOgsD25T0q0GlyD3N9M10gJkudHYxFtC', NULL, 0, NULL, 0, 'investor', NULL, NULL, 'not_started', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '5716478787541066', 0.00, NULL, NULL, NULL, NULL, NULL, '2025-12-03 14:08:54', '2025-12-03 14:09:17');

-- User 24: afnan ahmed
INSERT IGNORE INTO `users` (`ulid`, `name`, `avatar`, `status`, `receipt_screenshot`, `email`, `phone`, `email_verified_at`, `password`, `game_pin_hash`, `is_in_game`, `game_pin_locked_until`, `game_pin_failed_attempts`, `role`, `referral_code`, `reseller_id`, `kyc_status`, `kyc_id_type`, `kyc_id_number`, `kyc_full_name`, `kyc_id_front_path`, `kyc_id_back_path`, `kyc_selfie_path`, `kyc_submitted_at`, `kyc_approved_at`, `company_name`, `investment_capacity`, `experience`, `wallet_address`, `token_balance`, `coin_price`, `two_factor_secret`, `two_factor_recovery_codes`, `two_factor_confirmed_at`, `remember_token`, `created_at`, `updated_at`) 
VALUES (NULL, 'afnan ahmed', NULL, 'online', NULL, 'afnanzulfiqar12@gmail.com', '+923102449353', '2025-12-03 14:49:28', '$2y$12$ohmaTfi9a1R3XRuYJ3MR5O8TsNoPOJ0Ro1HR4gKZKGz0Bwazcx7v6', NULL, 0, NULL, 0, 'investor', NULL, NULL, 'not_started', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '8403865834459799', 0.00, NULL, NULL, NULL, NULL, NULL, '2025-12-03 14:48:52', '2025-12-03 14:49:28');

-- User 25: Muhammad Usman Siddique
INSERT IGNORE INTO `users` (`ulid`, `name`, `avatar`, `status`, `receipt_screenshot`, `email`, `phone`, `email_verified_at`, `password`, `game_pin_hash`, `is_in_game`, `game_pin_locked_until`, `game_pin_failed_attempts`, `role`, `referral_code`, `reseller_id`, `kyc_status`, `kyc_id_type`, `kyc_id_number`, `kyc_full_name`, `kyc_id_front_path`, `kyc_id_back_path`, `kyc_selfie_path`, `kyc_submitted_at`, `kyc_approved_at`, `company_name`, `investment_capacity`, `experience`, `wallet_address`, `token_balance`, `coin_price`, `two_factor_secret`, `two_factor_recovery_codes`, `two_factor_confirmed_at`, `remember_token`, `created_at`, `updated_at`) 
VALUES (NULL, 'Muhammad Usman Siddique', NULL, 'online', NULL, 'usmansiddiqu84@gmail.com', '+923007518607', '2025-12-03 16:33:33', '$2y$12$klGxBXf5bFKfS4YV9tdBFeIMTRSfuCIkI.IXnHwSMmohEdqe/xHI6', NULL, 0, NULL, 0, 'investor', NULL, NULL, 'not_started', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '3654729977899503', 0.00, NULL, NULL, NULL, NULL, NULL, '2025-12-03 16:33:05', '2025-12-03 16:33:33');

-- User 26: Altafkhan
INSERT IGNORE INTO `users` (`ulid`, `name`, `avatar`, `status`, `receipt_screenshot`, `email`, `phone`, `email_verified_at`, `password`, `game_pin_hash`, `is_in_game`, `game_pin_locked_until`, `game_pin_failed_attempts`, `role`, `referral_code`, `reseller_id`, `kyc_status`, `kyc_id_type`, `kyc_id_number`, `kyc_full_name`, `kyc_id_front_path`, `kyc_id_back_path`, `kyc_selfie_path`, `kyc_submitted_at`, `kyc_approved_at`, `company_name`, `investment_capacity`, `experience`, `wallet_address`, `token_balance`, `coin_price`, `two_factor_secret`, `two_factor_recovery_codes`, `two_factor_confirmed_at`, `remember_token`, `created_at`, `updated_at`) 
VALUES (NULL, 'Altafkhan', NULL, 'online', NULL, 'iltaf4581@gmail.com', '03467942302', '2025-12-03 16:55:50', '$2y$12$2Wxwm.k0t0q9.AXcilLaZuaPuW7vDl5F2j5orBM5icbIH6nw.VO4y', NULL, 0, NULL, 0, 'investor', NULL, NULL, 'not_started', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '4013968878954977', 0.00, NULL, NULL, NULL, NULL, NULL, '2025-12-03 16:54:57', '2025-12-03 16:55:50');

-- User 27: Muhammad Waqas
INSERT IGNORE INTO `users` (`ulid`, `name`, `avatar`, `status`, `receipt_screenshot`, `email`, `phone`, `email_verified_at`, `password`, `game_pin_hash`, `is_in_game`, `game_pin_locked_until`, `game_pin_failed_attempts`, `role`, `referral_code`, `reseller_id`, `kyc_status`, `kyc_id_type`, `kyc_id_number`, `kyc_full_name`, `kyc_id_front_path`, `kyc_id_back_path`, `kyc_selfie_path`, `kyc_submitted_at`, `kyc_approved_at`, `company_name`, `investment_capacity`, `experience`, `wallet_address`, `token_balance`, `coin_price`, `two_factor_secret`, `two_factor_recovery_codes`, `two_factor_confirmed_at`, `remember_token`, `created_at`, `updated_at`) 
VALUES (NULL, 'Muhammad Waqas', NULL, 'online', NULL, 'waqasjavaid1991@gmail.com', '+923097892394', '2025-12-03 20:28:20', '$2y$12$4Fun0S6p9YT6IO7eEkOBJudpoOcal60QeNB.HkYE6v8eCFqhN28SK', NULL, 0, NULL, 0, 'investor', NULL, NULL, 'pending', 'cnic', '3520216208803', 'Muhammad Waqas', 'kyc/83/cacxFnCq23jrcn9eerE8f7rfTQpkTom7JG6QIkAM.jpg', 'kyc/83/TifhJufsMo1mY8dNBmnR8SR2K8Z6ylEzVU1Xg485.jpg', 'kyc/83/ztK0U9NZ33JO5h9A4YXqGkEpmEX8c1AyEzixkEyw.jpg', '2025-12-03 20:32:07', NULL, NULL, NULL, NULL, '5416219320174399', 0.00, NULL, NULL, NULL, NULL, NULL, '2025-12-03 20:27:45', '2025-12-03 20:32:07');

-- User 28: Abdul Hanan
INSERT IGNORE INTO `users` (`ulid`, `name`, `avatar`, `status`, `receipt_screenshot`, `email`, `phone`, `email_verified_at`, `password`, `game_pin_hash`, `is_in_game`, `game_pin_locked_until`, `game_pin_failed_attempts`, `role`, `referral_code`, `reseller_id`, `kyc_status`, `kyc_id_type`, `kyc_id_number`, `kyc_full_name`, `kyc_id_front_path`, `kyc_id_back_path`, `kyc_selfie_path`, `kyc_submitted_at`, `kyc_approved_at`, `company_name`, `investment_capacity`, `experience`, `wallet_address`, `token_balance`, `coin_price`, `two_factor_secret`, `two_factor_recovery_codes`, `two_factor_confirmed_at`, `remember_token`, `created_at`, `updated_at`) 
VALUES (NULL, 'Abdul Hanan', NULL, 'online', NULL, 'malikhanni7@gmail.com', '+923069840702', '2025-12-04 08:23:37', '$2y$12$SQ5VDFX/uxremdcmwXe6RuC2fXnR26fs.pOlBESu7r2XkDqJ1wRNi', NULL, 0, NULL, 0, 'investor', NULL, NULL, 'not_started', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1783271501751767', 0.00, NULL, NULL, NULL, NULL, NULL, '2025-12-04 08:23:00', '2025-12-04 08:23:37');

-- User 29: Tanveershahid
INSERT IGNORE INTO `users` (`ulid`, `name`, `avatar`, `status`, `receipt_screenshot`, `email`, `phone`, `email_verified_at`, `password`, `game_pin_hash`, `is_in_game`, `game_pin_locked_until`, `game_pin_failed_attempts`, `role`, `referral_code`, `reseller_id`, `kyc_status`, `kyc_id_type`, `kyc_id_number`, `kyc_full_name`, `kyc_id_front_path`, `kyc_id_back_path`, `kyc_selfie_path`, `kyc_submitted_at`, `kyc_approved_at`, `company_name`, `investment_capacity`, `experience`, `wallet_address`, `token_balance`, `coin_price`, `two_factor_secret`, `two_factor_recovery_codes`, `two_factor_confirmed_at`, `remember_token`, `created_at`, `updated_at`) 
VALUES (NULL, 'Tanveershahid', NULL, 'online', NULL, 'tanveershahid800@gmail.com', '03218077683', '2025-12-04 13:39:05', '$2y$12$70y5q/8OolPGLiLaAke5leopnc2c3.ZR3XdLWhczhyanJA6hok1EC', NULL, 0, NULL, 0, 'investor', NULL, NULL, 'not_started', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '9183722443099097', 0.00, NULL, NULL, NULL, NULL, '0Wt2sdkD77E1sRLfRHnlNXGRAel0CfwHkkSGfw4msdhKQjQGugDBBFH3HfMm', '2025-12-04 13:38:30', '2025-12-04 13:39:05');

-- User 30: Muhammad Mudasir
INSERT IGNORE INTO `users` (`ulid`, `name`, `avatar`, `status`, `receipt_screenshot`, `email`, `phone`, `email_verified_at`, `password`, `game_pin_hash`, `is_in_game`, `game_pin_locked_until`, `game_pin_failed_attempts`, `role`, `referral_code`, `reseller_id`, `kyc_status`, `kyc_id_type`, `kyc_id_number`, `kyc_full_name`, `kyc_id_front_path`, `kyc_id_back_path`, `kyc_selfie_path`, `kyc_submitted_at`, `kyc_approved_at`, `company_name`, `investment_capacity`, `experience`, `wallet_address`, `token_balance`, `coin_price`, `two_factor_secret`, `two_factor_recovery_codes`, `two_factor_confirmed_at`, `remember_token`, `created_at`, `updated_at`) 
VALUES (NULL, 'Muhammad Mudasir', NULL, 'online', NULL, 'mudasirrandhawa652@gmail.com', '+923024559790', '2025-12-05 13:38:50', '$2y$12$9kjn0m9jI2tCxvCH.tU31ezWg/FnbjbalmcN/K80aCszbUZximWlG', NULL, 0, NULL, 0, 'investor', NULL, NULL, 'not_started', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '9282430667892381', 0.00, NULL, NULL, NULL, NULL, NULL, '2025-12-05 13:36:55', '2025-12-05 13:38:50');

-- User 31: Shahid nazir
INSERT IGNORE INTO `users` (`ulid`, `name`, `avatar`, `status`, `receipt_screenshot`, `email`, `phone`, `email_verified_at`, `password`, `game_pin_hash`, `is_in_game`, `game_pin_locked_until`, `game_pin_failed_attempts`, `role`, `referral_code`, `reseller_id`, `kyc_status`, `kyc_id_type`, `kyc_id_number`, `kyc_full_name`, `kyc_id_front_path`, `kyc_id_back_path`, `kyc_selfie_path`, `kyc_submitted_at`, `kyc_approved_at`, `company_name`, `investment_capacity`, `experience`, `wallet_address`, `token_balance`, `coin_price`, `two_factor_secret`, `two_factor_recovery_codes`, `two_factor_confirmed_at`, `remember_token`, `created_at`, `updated_at`) 
VALUES (NULL, 'Shahid nazir', NULL, 'online', NULL, 'akansbj@gmail.com', '+923404550622', '2025-12-05 14:12:24', '$2y$12$9QIj8yx7SUW8NbN6lpu/wuC74itmxs8TBEJsYCwswZlNsUAtyhHQK', NULL, 0, NULL, 0, 'investor', NULL, NULL, 'not_started', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1158914583355195', 0.00, NULL, NULL, NULL, NULL, NULL, '2025-12-05 14:11:19', '2025-12-05 14:12:24');

-- User 32: Muhammad Younas
INSERT IGNORE INTO `users` (`ulid`, `name`, `avatar`, `status`, `receipt_screenshot`, `email`, `phone`, `email_verified_at`, `password`, `game_pin_hash`, `is_in_game`, `game_pin_locked_until`, `game_pin_failed_attempts`, `role`, `referral_code`, `reseller_id`, `kyc_status`, `kyc_id_type`, `kyc_id_number`, `kyc_full_name`, `kyc_id_front_path`, `kyc_id_back_path`, `kyc_selfie_path`, `kyc_submitted_at`, `kyc_approved_at`, `company_name`, `investment_capacity`, `experience`, `wallet_address`, `token_balance`, `coin_price`, `two_factor_secret`, `two_factor_recovery_codes`, `two_factor_confirmed_at`, `remember_token`, `created_at`, `updated_at`) 
VALUES (NULL, 'Muhammad Younas', NULL, 'online', NULL, 'mhryounuskhan@gmail.com', '0308618979066', '2025-12-06 04:51:10', '$2y$12$1X5bdc2qoW4OAvpu4a8lQOdmhVGLl/Rzi7iBl9wE4BVe3FJRs5QHW', NULL, 0, NULL, 0, 'investor', NULL, NULL, 'not_started', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1472629784145644', 0.00, NULL, NULL, NULL, NULL, NULL, '2025-12-06 04:50:20', '2025-12-06 04:51:10');

-- User 33: Malik Muhammad Qasim
INSERT IGNORE INTO `users` (`ulid`, `name`, `avatar`, `status`, `receipt_screenshot`, `email`, `phone`, `email_verified_at`, `password`, `game_pin_hash`, `is_in_game`, `game_pin_locked_until`, `game_pin_failed_attempts`, `role`, `referral_code`, `reseller_id`, `kyc_status`, `kyc_id_type`, `kyc_id_number`, `kyc_full_name`, `kyc_id_front_path`, `kyc_id_back_path`, `kyc_selfie_path`, `kyc_submitted_at`, `kyc_approved_at`, `company_name`, `investment_capacity`, `experience`, `wallet_address`, `token_balance`, `coin_price`, `two_factor_secret`, `two_factor_recovery_codes`, `two_factor_confirmed_at`, `remember_token`, `created_at`, `updated_at`) 
VALUES (NULL, 'Malik Muhammad Qasim', NULL, 'online', NULL, 'malikqasimbrother@gmail.com', '+923454442814', '2025-12-06 09:12:40', '$2y$12$yx1Uq9Wa9nA51VnL8ZXDg.cHerE8Pd81RB/qkLIJZggM5lY7xIAS2', NULL, 0, NULL, 0, 'investor', NULL, NULL, 'not_started', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '5710281941164374', 0.00, NULL, NULL, NULL, NULL, NULL, '2025-12-06 09:12:01', '2025-12-06 09:12:40');

-- User 34: Muhammad Farhan
INSERT IGNORE INTO `users` (`ulid`, `name`, `avatar`, `status`, `receipt_screenshot`, `email`, `phone`, `email_verified_at`, `password`, `game_pin_hash`, `is_in_game`, `game_pin_locked_until`, `game_pin_failed_attempts`, `role`, `referral_code`, `reseller_id`, `kyc_status`, `kyc_id_type`, `kyc_id_number`, `kyc_full_name`, `kyc_id_front_path`, `kyc_id_back_path`, `kyc_selfie_path`, `kyc_submitted_at`, `kyc_approved_at`, `company_name`, `investment_capacity`, `experience`, `wallet_address`, `token_balance`, `coin_price`, `two_factor_secret`, `two_factor_recovery_codes`, `two_factor_confirmed_at`, `remember_token`, `created_at`, `updated_at`) 
VALUES (NULL, 'Muhammad Farhan', NULL, 'online', NULL, 'farhanqasim332@gmail.com', '+923145871381', '2025-12-06 13:27:12', '$2y$12$eqLhwATJkpQlqklL.C3ciuCzvPA0g4DflhXJfQ1RCJxV.XGdUallq', NULL, 0, NULL, 0, 'investor', NULL, NULL, 'not_started', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '3484796556075286', 0.00, NULL, NULL, NULL, NULL, NULL, '2025-12-06 13:26:44', '2025-12-06 13:27:12');

-- User 35: Muhammad Ali siddiqui
INSERT IGNORE INTO `users` (`ulid`, `name`, `avatar`, `status`, `receipt_screenshot`, `email`, `phone`, `email_verified_at`, `password`, `game_pin_hash`, `is_in_game`, `game_pin_locked_until`, `game_pin_failed_attempts`, `role`, `referral_code`, `reseller_id`, `kyc_status`, `kyc_id_type`, `kyc_id_number`, `kyc_full_name`, `kyc_id_front_path`, `kyc_id_back_path`, `kyc_selfie_path`, `kyc_submitted_at`, `kyc_approved_at`, `company_name`, `investment_capacity`, `experience`, `wallet_address`, `token_balance`, `coin_price`, `two_factor_secret`, `two_factor_recovery_codes`, `two_factor_confirmed_at`, `remember_token`, `created_at`, `updated_at`) 
VALUES (NULL, 'Muhammad Ali siddiqui', NULL, 'online', NULL, 'siddali432@gmail.com', '+923408299306', NULL, '$2y$12$kA.w.B0HFjlyuUk1bh7hMe2mi0xhu/tCmKxADbM5/Mb/BOQCKuwF2', NULL, 0, NULL, 0, 'investor', NULL, NULL, 'not_started', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '5724911505537651', 0.00, NULL, NULL, NULL, NULL, NULL, '2025-12-06 13:53:55', '2025-12-06 13:53:55');

-- User 36: Muhammad Ali siddiqui (second)
INSERT IGNORE INTO `users` (`ulid`, `name`, `avatar`, `status`, `receipt_screenshot`, `email`, `phone`, `email_verified_at`, `password`, `game_pin_hash`, `is_in_game`, `game_pin_locked_until`, `game_pin_failed_attempts`, `role`, `referral_code`, `reseller_id`, `kyc_status`, `kyc_id_type`, `kyc_id_number`, `kyc_full_name`, `kyc_id_front_path`, `kyc_id_back_path`, `kyc_selfie_path`, `kyc_submitted_at`, `kyc_approved_at`, `company_name`, `investment_capacity`, `experience`, `wallet_address`, `token_balance`, `coin_price`, `two_factor_secret`, `two_factor_recovery_codes`, `two_factor_confirmed_at`, `remember_token`, `created_at`, `updated_at`) 
VALUES (NULL, 'Muhammad Ali siddiqui', NULL, 'online', NULL, 'sid252093@gmail.com', '+923122564055', '2025-12-06 13:59:50', '$2y$12$D5Ws1mjWTyY2dbng26LvbOwemuTjNH0WKJotM4oJ4Z3x9H.PZgWwi', NULL, 0, NULL, 0, 'investor', NULL, NULL, 'not_started', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '5350850502777968', 0.00, NULL, NULL, NULL, NULL, NULL, '2025-12-06 13:59:29', '2025-12-06 13:59:50');

-- User 37: Adnan Shahzad
INSERT IGNORE INTO `users` (`ulid`, `name`, `avatar`, `status`, `receipt_screenshot`, `email`, `phone`, `email_verified_at`, `password`, `game_pin_hash`, `is_in_game`, `game_pin_locked_until`, `game_pin_failed_attempts`, `role`, `referral_code`, `reseller_id`, `kyc_status`, `kyc_id_type`, `kyc_id_number`, `kyc_full_name`, `kyc_id_front_path`, `kyc_id_back_path`, `kyc_selfie_path`, `kyc_submitted_at`, `kyc_approved_at`, `company_name`, `investment_capacity`, `experience`, `wallet_address`, `token_balance`, `coin_price`, `two_factor_secret`, `two_factor_recovery_codes`, `two_factor_confirmed_at`, `remember_token`, `created_at`, `updated_at`) 
VALUES (NULL, 'Adnan Shahzad', NULL, 'online', NULL, 'daniawaramundadaniawaramunda@gmail.com', '+923198907020', NULL, '$2y$12$FeJ84HpmHuoUXylHr6Y6FuOMjRuLP2H54dcwIyMDtFN9O8qyo97Ci', NULL, 0, NULL, 0, 'investor', NULL, NULL, 'not_started', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '8083874152395839', 0.00, NULL, NULL, NULL, NULL, NULL, '2025-12-06 18:17:40', '2025-12-06 18:17:40');

-- User 38: Abdul Basit
INSERT IGNORE INTO `users` (`ulid`, `name`, `avatar`, `status`, `receipt_screenshot`, `email`, `phone`, `email_verified_at`, `password`, `game_pin_hash`, `is_in_game`, `game_pin_locked_until`, `game_pin_failed_attempts`, `role`, `referral_code`, `reseller_id`, `kyc_status`, `kyc_id_type`, `kyc_id_number`, `kyc_full_name`, `kyc_id_front_path`, `kyc_id_back_path`, `kyc_selfie_path`, `kyc_submitted_at`, `kyc_approved_at`, `company_name`, `investment_capacity`, `experience`, `wallet_address`, `token_balance`, `coin_price`, `two_factor_secret`, `two_factor_recovery_codes`, `two_factor_confirmed_at`, `remember_token`, `created_at`, `updated_at`) 
VALUES (NULL, 'Abdul Basit', NULL, 'online', NULL, 'abdulbassit41@gmail.com', '03440755979', '2025-12-06 19:05:10', '$2y$12$qxJAIYVbQAz3QmASm2zQPOvLGCXxjepPRmFWk93BfC3UIor83dpii', NULL, 0, NULL, 0, 'investor', NULL, NULL, 'not_started', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '9166992982751842', 0.00, NULL, NULL, NULL, NULL, NULL, '2025-12-06 19:04:42', '2025-12-06 19:05:10');

-- User 39: Muhammed faizan
INSERT IGNORE INTO `users` (`ulid`, `name`, `avatar`, `status`, `receipt_screenshot`, `email`, `phone`, `email_verified_at`, `password`, `game_pin_hash`, `is_in_game`, `game_pin_locked_until`, `game_pin_failed_attempts`, `role`, `referral_code`, `reseller_id`, `kyc_status`, `kyc_id_type`, `kyc_id_number`, `kyc_full_name`, `kyc_id_front_path`, `kyc_id_back_path`, `kyc_selfie_path`, `kyc_submitted_at`, `kyc_approved_at`, `company_name`, `investment_capacity`, `experience`, `wallet_address`, `token_balance`, `coin_price`, `two_factor_secret`, `two_factor_recovery_codes`, `two_factor_confirmed_at`, `remember_token`, `created_at`, `updated_at`) 
VALUES (NULL, 'Muhammed faizan', NULL, 'online', NULL, 'faizankhanfaizankhan111987@gmail.com', '03452425005', '2025-12-07 17:26:58', '$2y$12$tLdwkL23D53mXOuUTyWqHuCDjbfrSrDkBDnP8dSre/PrPIV3mFlOS', NULL, 0, NULL, 0, 'investor', NULL, NULL, 'not_started', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1065066640082525', 0.00, NULL, NULL, NULL, NULL, NULL, '2025-12-07 17:26:24', '2025-12-07 17:26:58');

-- User 40: Bashir Ahmed
INSERT IGNORE INTO `users` (`ulid`, `name`, `avatar`, `status`, `receipt_screenshot`, `email`, `phone`, `email_verified_at`, `password`, `game_pin_hash`, `is_in_game`, `game_pin_locked_until`, `game_pin_failed_attempts`, `role`, `referral_code`, `reseller_id`, `kyc_status`, `kyc_id_type`, `kyc_id_number`, `kyc_full_name`, `kyc_id_front_path`, `kyc_id_back_path`, `kyc_selfie_path`, `kyc_submitted_at`, `kyc_approved_at`, `company_name`, `investment_capacity`, `experience`, `wallet_address`, `token_balance`, `coin_price`, `two_factor_secret`, `two_factor_recovery_codes`, `two_factor_confirmed_at`, `remember_token`, `created_at`, `updated_at`) 
VALUES (NULL, 'Bashir Ahmed', NULL, 'online', NULL, 'ahmedbashiryahoo56@gmail.com', '923343052849', '2025-12-08 06:33:57', '$2y$12$ZLOKgYiONk9cb83RovPnuOsUbD2qxcbCaSfcbCvDrMDnwD74id842', NULL, 0, NULL, 0, 'investor', NULL, NULL, 'not_started', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2770969496353273', 0.00, NULL, NULL, NULL, NULL, NULL, '2025-12-08 06:33:20', '2025-12-08 06:33:57');

-- After inserting all users, run this to backfill ULIDs:
-- php artisan users:sync-missing
-- OR manually generate ULIDs using Laravel's Str::ulid() helper
